theme: jekyll-theme-architect
title: RESTful News
description: Open source news API for quants.
show_sidebar: true
urls:
  github_org: https://github.com/restfulnews
  website_repo: https://github.com/restfulnews/restfulnews.com
  api_repo: https://github.com/restfulnews/api