theme: jekyll-theme-architect
title: RESTful News
description: Source News API / Analytics Platform.
show_sidebar: true
urls:
  api_docs: https://docs.restfulnews.com/
  github_org: https://github.com/restfulnews
  website_repo: https://github.com/restfulnews/restfulnews.com
  api_repo: https://github.com/restfulnews/api
  app_repo: https://github.com/restfulnews/app.restfulnews.com

collections:
  _blog:
    output: true
    permalink: /blog/:title/