theme: jekyll-theme-architect
title: RESTful News
description: Retrieve news articles about Australian companies.
show_sidebar: true
github:
  docs: /docs
  zip_url: https://github.com/mrchrisjoy/restful-news/archive/master.zip
